### ISSUE TITLE
DOM Elements are selected when clicked

### ISSUE THREAD

**Issue by psycrowStudio** [mixer/arcade-machine#62]
I believe this issue is multifaceted:

When clicking (via mouse) on items (DIV, UL, SPAN, etc.),  these items can be selected (gets the 'arc--selected-direct' class). I would not expect this to even be possible due to the documentation: 

> You must define arc directive on element which you want to be focusable that are not otherwise focusable, or when you want to define custom logic. That is, anything except the following tags:

To prevent this, I have attempted:
- no 'arc' class added
- added tabIndex="-1"
**- [arc-exclude-this]="true", [arc-exclude]="true"** - These two options cause the Angular compile to fail with the following error:
  - "Can't bind to 'arc-exclude-this' since it isn't a known property of 'ul'." (I have the fill trace I can provide).

Just getting comfortable with how this system works and how to properly setup the DOM.

**Comment by saadataz** [comment]
@psycrowStudio you cannot use any arc directives (`[arc-exclude]` etc) without the arc` directive.
By default none of the elements are selectable unless you explicitly specify tabIndex="0"

**Comment by psycrowStudio** [comment]
I am observing that virtually all elements are selectable (especially in response to mouse click events).

**Comment by connor4312** [comment]
What browser are you using? The only external document event we listen to is [`focusin`](https://github.com/WatchBeam/arcade-machine/blob/master/src/input.service.ts#L361). If the browser says an element is focused, we'll focus it, but most well-behaved browsers should not do this.

**Comment by psycrowStudio** [comment]
Using Edge (the only one that works with xbox controller).

After playing with this all day, its apparent that mousing behavior and controller behavior do not co-exist well. Certain things like removing tabIndex will help for DPad Nav but break for mouse mode. 

In any case the behavior does not seem consistent with the documentation (as many if not all elements are selectable in various edge scenarios).

**Comment by saadataz** [comment]
@psycrowStudio afaik we cannot prevent browser from focusing element using mouse.
Arcade machine requires the knowledge of last selected element to figure out the next focusable element, therefore it keeps track of focusin events not generated by itself [here](https://github.com/mixer/arcade-machine/blob/master/src/input.service.ts#L358)
